homework3
krisnovitskaya/edu_java2 pull request #3
Opened 2020-02-28 19:11 UTC by krisnovitskaya

2020-03-03 07:19 UTC, OKrylov requested changes
В целом все отлично, но есть пара мелких замечаний

2020-03-03 07:19 UTC, OKrylov commented on src/les03/PartOne.java
> +            for (int i = 0; i < arr.length ; i++) {
второй цикл здесь лишний, мы можем получать уже сохраненные данные из мэпы

2020-03-03 07:19 UTC, OKrylov commented on src/les03/phonebook/Phonebook.java
> +    void add(int phoneNumber, String surname ){
не забывайте про модификаторы доступа, нужно добавить public

2020-03-03 07:19 UTC, OKrylov commented on src/les03/phonebook/Phonebook.java
> +    ArrayList<Integer> get(String surname){
не забывайте про модификаторы доступа, нужно добавить public

2020-03-03 07:19 UTC, OKrylov commented on src/les03/phonebook/Phonebook.java
> +        for (Map.Entry<Integer, String> entry : this.data.entrySet()) {
в данном методе можно уйти от цикла, если в качестве ключа коллекции будет фамилия, а значение - множество номеров телефонов

2020-03-08 23:02 UTC, okrylov-axcient approved these changes
По ДЗ все отлично, замечаний нет

2020-03-09 15:34 UTC, merged